### ISSUE TITLE
Reusable Template creation failing

### ISSUE THREAD

**Issue by jlnabais** [lightweightdjango/examples#1]
First of all, great  book (so far).

When I use the command suggested in the book: 

```
django-admin.py startproject foo --template=project_name
```

I get the following error message (even when I download your code example): 
_CommandError: couldn't handle project template project_name._

Thanks in advance,
João.

**Comment by mlavin** [comment]
I can't reproduce this issue. Here are the exact steps I used with this example repo. You can skip the first few if you've already created a virtualenv and installed Django (which it appears you already have)

```
$ mkvirtualenv examples -p /usr/bin/python3.4
(examples) $ pip install Django==1.7.1
(examples) $ git clone git@github.com:lightweightdjango/examples.git
(examples) $ cd examples
(examples) $ git checkout chapter-1
(examples) $ django-admin.py startproject foo --template=project_name
```

Listing the current directory shows the new `foo` project.

```
(examples) $ tree
.
├── foo
│   └── foo.py
├── hello.py
├── project_name
│   └── project_name.py
└── README.rst

2 directories, 4 files
```

**Comment by jlnabais** [comment]
It's working now! =D

Thank you!

**Comment by mlavin** [comment]
Happy to help and hope you enjoy the book!

**Comment by martin-martin** [comment]
Hello! I'm getting the same error when attempting to run startproject with this template on Django 2.x

I know it wasn't designed for that, but I haven't found a good tutorial or pointers on how to make project templates on 2.x

@mlavin do you know what is breaking your template in newer Django/Python versions, and how this could be approached in Django 2 upwards?

I've been trying to use it with Python 3.6 and Django 2.1

Any pointers are greatly appreciated!

**Comment by nobism** [comment]
I'm also getting this error with Django 1.7.
