### ISSUE TITLE
Page 125 Chapter 5

### ISSUE THREAD

**Issue by shopsmartin** [lightweightdjango/examples#13]
I cannot get the authentication to let me through after submitting the form.  I keep getting a 403 error, saying the CSRF token is missing. Searching shows I should add 

``` python
{% csrf_token %}
```

to my form post method. I am unable to find the source of this error after comparing my code to yours. I'm totally unable to figure out why I can't get past this. 

I've gotten to the styled login template successfully rendering.

**Comment by mlavin** [comment]
The CSRF token is inserted in the header of AJAX requests by https://github.com/lightweightdjango/examples/blob/chapter-5/scrum/board/static/board/js/models.js#L27 (added on page 110). I can't reproduce this error and there isn't sufficient information here to debug this for you. If Django's error page isn't giving you sufficient help you should check your browser's dev tools to see the requests which were made and if there were any JS related errors.
