### ISSUE TITLE
Chapter 1/2 Create a New Project

### ISSUE THREAD

**Issue by jpanknin** [lightweightdjango/examples#19]
When I create a new project with the command:

django-admin.py startproject foo --template=project_name

or:

django-admin.py startproject placeholder --template=project_name

I get:

CommandError: couldn't handle project template project_name.

The command is creating a folder named "foo" and "placeholder," but it's not creating the .py file within them.  I know you provided your code for checkout, but I'd rather figure out why this isn't working.  Full code snippet is below:

```
import os
import sys

from django.conf import settings

DEBUG = os.environ.get('DEBUG', 'on') == 'on'

SECRET_KEY = os.environ.get('SECRET_KEY', '{{ secret_key }}')

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost').split(',')


settings.configure(
    DEBUG=DEBUG,
    SECRET_KEY=SECRET_KEY,
    ALLOWED_HOSTS=ALLOWED_HOSTS,
    ROOT_URLCONF=__name__,
    MIDDLEWARE_CLASSES=(
        'django.middleware.common.CommonMiddleware',
        'django.middleware.csrf.CsrfViewMiddleware',
        'django.middleware.clickjacking.XFrameOptionsMiddleware',
        ),
    )


from django.conf.urls import url
from django.core.wsgi import get_wsgi_application
from django.http import HttpResponse


def index(request):
    return HttpResponse('Hello World')

urlpatterns = (
    url(r'^$', index),
    )

application = get_wsgi_application()

if __name__ == "__main__":
    from django.core.management import execute_from_command_line

    execute_from_command_line(sys.argv)
```

**Comment by mlavin** [comment]
Take a look at #1. You need to ensure you have the directory structure matching the examples as well as execute the command in the directory which matches the relative path reference for the `project_name` folder.

**Comment by jpanknin** [comment]
Worked.  Moved up one directory level and re-ran.  2 hours of messing with that and it took 20 seconds to fix......  Thanks for the help.
