### ISSUE TITLE
scrum: validate_end() missing 1 required positional argument: 'source'

### ISSUE THREAD

**Issue by dawidp** [lightweightdjango/examples#2]
After fixing error:

```
It is redundant to specify `get_links` on SerializerMethodField 'links' in serializer 'SprintSerializer',
because it is the same as the default method name. Remove the `method_name` argument.
```

in class SprintSerializer and TaskSerializer with links, status_display fields I got stuck with this error:

```
TypeError at /api/sprints/
validate_end() missing 1 required positional argument: 'source'
Request Method: POST
Request URL:    http://localhost:8000/api/sprints/
Django Version: 1.7.1
Exception Type: TypeError
Exception Value:    validate_end() missing 1 required positional argument: 'source'
Exception Location: /home/dade/.virtuaenvs/kikiri-test/lib/python3.4/site-packages/rest_framework/serializers.py in to_internal_value, line 362
Python Executable:  /home/dade/.virtuaenvs/kikiri-test/bin/python
Python Version: 3.4.0
Python Path:    
['/home/dade/projects/python/kikiri-test-django/scrum',
 '/home/dade/.virtuaenvs/kikiri-test/lib/python3.4',
 '/home/dade/.virtuaenvs/kikiri-test/lib/python3.4/plat-x86_64-linux-gnu',
 '/home/dade/.virtuaenvs/kikiri-test/lib/python3.4/lib-dynload',
 '/usr/lib/python3.4',
 '/usr/lib/python3.4/plat-x86_64-linux-gnu',
 '/home/dade/.virtuaenvs/kikiri-test/lib/python3.4/site-packages']
Server time:    Thu, 18 Dec 2014 02:16:36 +0000
```

this happens when I try to post a sprint with due date set to 01/12/2014. Firstly I thought this was my type error but after cloning examples got the same error.

**Comment by dawidp** [comment]
I think I've found the problem(s): I was using following versions of Django and Django Rest Framework: 

```
Django==1.7.1
djangorestframework==3.0.1
```

while these examples were build (probably) using: 

```
Django==1.7
djangorestframework==2.4.4
```

I think it would be good idea to add `requirements.txt` with versions of the packages

**Comment by mlavin** [comment]
You are correct. The book was written for Django Rest Framework 2.X and isn't compatible with the latest serializer changes in 3.X. We'll update to make that more explicit.

**Comment by Copser** [comment]
Great book by the way, @dawidp and @mlavin, tank you for clearing this out for me...;-D

**Comment by ghost** [comment]
Thank you so much guys.... :+1:

**Comment by gddk** [comment]
ditto the thank you, I've been enjoying coding the examples and learning rest_framework.  I too ran into the 3 vs 2 problem with validation, but figured out how to convert to v3 style.  See https://github.com/djangopractice/scrum/blob/17c3b8b2850aa7d8aa1d3fecd38f0b654dfa2744/board/serializers.py for rest framework v3 style validation.

**Comment by mlavin** [comment]
@juliaelman and I have been trying to figure out the best way to address this, particularly for those who have print copies of the book. We want to keep this repo in line with the book and any submitted corrections so we can't just fix it here. There are a bunch of little changes which aren't too difficult to follow if you read the 3.0 release notes but might be tedious in the errata. The easiest correction/errata would be to say `pip install djangorestframework<3.0` in the chapter but that feels like a bit of a cop out. If anyone has thoughts or feelings about a note/correction that would save people some heart ache when working through this chapter we'd love to hear them.

**Comment by shopsmartin** [comment]
I got as far as this also, but my error is the same, coming from a slightly different line in /rest-framwork/serializers.py, although it still says validate() needs a source parameter. Comes from the perform_validation method. 

I've gone back and made sure I am using Django 1.7 and djangorestframework 2.4.4, but the error still occurs.

```python
POST
Request URL:	http://localhost:8000/api/sprints/
Django Version:	1.7
Exception Type:	TypeError
Exception Value:	
validate() missing 1 required positional argument: 'source'
Exception Location:	/Users/martinschilling/.virtualenvs/shopsmartin/lib/python3.4/site-packages/rest_framework/serializers.py in perform_validation, line 316
Python Executable:	/Users/martinschilling/.virtualenvs/shopsmartin/bin/python
Python Version:	3.4.1
Python Path:	
['/Users/martinschilling/PycharmProjects/scrum',
 '/Users/martinschilling/.virtualenvs/shopsmartin/lib/python3.4/site-packages/setuptools-1.1.5-py3.4.egg',
 '/Users/martinschilling/.virtualenvs/shopsmartin/lib/python3.4/site-packages/pip-1.4.1-py3.4.egg',
 '/Users/martinschilling/PycharmProjects/scrum',
 '/Library/Frameworks/Python.framework/Versions/3.4/lib/python34.zip',
 '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4',
 '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/plat-darwin',
 '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/lib-dynload',
 '/Users/martinschilling/.virtualenvs/shopsmartin/lib/python3.4/site-packages']
Server time:	Fri, 16 Jan 2015 20:07:32 +0000
```

**Comment by mlavin** [comment]
We've pushed updates and confirmed the errata for the known issues related to Django REST Framework 3.0.X: https://github.com/lightweightdjango/examples/compare/396eb56e96...bbf88e2076

Thank you to everyone who reported this issue and those who submitted fixes. I know it was helpful for our readers to be able to find those before we were able to make the updates.
