### ISSUE TITLE
Xhr responseJSON Property

### ISSUE THREAD

**Issue by anhlt** [lightweightdjango/examples#4]
The standard XMLHttpRequest has no responseJSON property. So in this file:
[views.js](https://github.com/lightweightdjango/examples/blob/chapter-6/scrum/board/static/board/js/views.js)

``` js
 failure: function (xhr, status, error) {
var errors = xhr.responseJSON;
this.showErrors(errors);
}
```

must be change to 
`var errors = JSON.parse(xhr.responseText);`

**Comment by mlavin** [comment]
This isn't a standard XMLHttpRequest. It's jQuery's wrapped version of XMLHttpRequest. See http://api.jquery.com/jquery.ajax/ under the section "Data Types":

> The parsed JSON object is made available through the responseJSON property of the jqXHR object.
