### ISSUE TITLE
Problem when update to redis.

### ISSUE THREAD

**Issue by anhlt** [lightweightdjango/examples#5]
```
 onmessage: function (message) {
var result = JSON.parse(message.data);
this.trigger('message', result, message);
if (result.model && result.action) {
this.trigger(result.model + ':' + result.action,
result.id, result, message);
}
},
```

onmessage function still use, result.model. But in watercooler. Message format have been changed to:

```
 message = json.dumps({
'sender': sender and sender.uid,
'message': message
})
```

So it can't trigger onmessage/

**Comment by mlavin** [comment]
The `RedisSubscriber` unwraps the message from the publisher before pushing it to the websocket. See https://github.com/lightweightdjango/examples/blob/chapter-8/scrum/watercooler.py#L37
