### ISSUE TITLE
Chapter 4: Error in forms.py (Chapter 4)

### ISSUE THREAD

**Issue by giancarlocp** [lightweightdjango/examples#9]
`Exception Value:   super() takes at least 1 argument (0 given)`

Replace:
`super().__init__(*args, **kwargs)`
With:
`super(TaskFilter, self).__init__(*args, **kwargs)`

https://github.com/lightweightdjango/examples/blob/chapter-4/scrum/board/forms.py#L39

**Comment by mlavin** [comment]
Looks like you are using Python 2.7. The book and these examples are written for Python 3.3+. See PEP 3135 https://www.python.org/dev/peps/pep-3135/ to see the updated `super` syntax for Python 3.
